/** One primary executable check for every checkbox in fixture/spec.md. */
export type SpecMatrixRow = {
  id: `${"A" | "B" | "C" | "D" | "E" | "F" | "G" | "H"}.${number}`;
  spec: string;
  primary: string;
  testFile: string;
};

export const SPEC_MATRIX: readonly SpecMatrixRow[] = [
  { id: "A.1", spec: "returned status", primary: "A.returned", testFile: "unit/loans.test.ts" },
  { id: "A.2", spec: "overdue status", primary: "A.overdue", testFile: "unit/loans.test.ts" },
  { id: "A.3", spec: "due-soon status", primary: "A.due-soon", testFile: "unit/loans.test.ts" },
  { id: "A.4", spec: "ok status", primary: "A.ok", testFile: "unit/loans.test.ts" },
  { id: "A.5", spec: "due-at-now boundary", primary: "A.boundary", testFile: "unit/loans.test.ts" },
  { id: "B.1", spec: "card name and category", primary: "B.name-category", testFile: "e2e/catalogue.spec.ts" },
  { id: "B.2", spec: "availability badge", primary: "B.badge", testFile: "e2e/catalogue.spec.ts" },
  { id: "B.3", spec: "card item link", primary: "B.link", testFile: "e2e/catalogue.spec.ts" },
  { id: "B.4", spec: "item image alternative text", primary: "B.image-alt", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.1", spec: "all catalogue items and open loans", primary: "C.renders-all", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.2", spec: "case-insensitive q filter", primary: "C.filter-q", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.3", spec: "exact category filter", primary: "C.filter-category", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.4", spec: "intersecting q and category filters", primary: "C.filter-both", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.5", spec: "empty catalogue result", primary: "C.empty", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.6", spec: "Items heading", primary: "C.renders", testFile: "e2e/catalogue.spec.ts" },
  { id: "C.7", spec: "parallel count and category reads", primary: "C.parallel-reads", testFile: "e2e/catalogue.spec.ts" },
  { id: "D.1", spec: "detail name category and description", primary: "D.renders", testFile: "e2e/detail.spec.ts" },
  { id: "D.2", spec: "newest-first loan history and statuses", primary: "D.history-order", testFile: "e2e/detail.spec.ts" },
  { id: "D.3", spec: "unknown item not-found", primary: "D.notfound", testFile: "e2e/detail.spec.ts" },
  { id: "D.4", spec: "checkout only when available", primary: "D.form-hidden", testFile: "e2e/detail.spec.ts" },
  { id: "D.5", spec: "return only when on loan", primary: "D.return-visible", testFile: "e2e/detail.spec.ts" },
  { id: "D.6", spec: "item metadata title", primary: "D.metadata", testFile: "e2e/detail.spec.ts" },
  { id: "E.1", spec: "all member options and due-date input", primary: "E.member-options", testFile: "e2e/detail.spec.ts" },
  { id: "E.2", spec: "checkout action submission", primary: "E.submits", testFile: "e2e/detail.spec.ts" },
  { id: "E.3", spec: "checkout pending control", primary: "E.pending", testFile: "e2e/detail.spec.ts" },
  { id: "E.4", spec: "checkout optimistic update", primary: "E.optimistic", testFile: "e2e/detail.spec.ts" },
  { id: "E.5", spec: "checkout action error", primary: "E.error-shown", testFile: "e2e/detail.spec.ts" },
  { id: "E.6", spec: "return control and action submission", primary: "E.return-submits", testFile: "e2e/detail.spec.ts" },
  { id: "E.7", spec: "return pending control", primary: "E.return-pending", testFile: "e2e/detail.spec.ts" },
  { id: "E.8", spec: "return optimistic update", primary: "E.return-optimistic", testFile: "e2e/detail.spec.ts" },
  { id: "E.9", spec: "return action error", primary: "E.return-error", testFile: "e2e/detail.spec.ts" },
  { id: "F.1", spec: "checkout records now and due date", primary: "F.checkout-record", testFile: "e2e/detail.spec.ts" },
  { id: "F.2", spec: "return records now", primary: "F.return-record", testFile: "e2e/detail.spec.ts" },
  { id: "F.3", spec: "checkout action authorization", primary: "F.auth-checkout", testFile: "e2e/detail.spec.ts" },
  { id: "F.4", spec: "checkout on-loan conflict", primary: "F.checkout-conflict", testFile: "e2e/detail.spec.ts" },
  { id: "F.5", spec: "checkout future due-date guard", primary: "F.future-due-date", testFile: "e2e/detail.spec.ts" },
  { id: "F.6", spec: "return no-open-loan guard", primary: "F.return-not-on-loan", testFile: "e2e/detail.spec.ts" },
  { id: "F.7", spec: "post-mutation list and detail state", primary: "F.post-mutation-state", testFile: "e2e/detail.spec.ts" },
  { id: "G.1", spec: "GET 200 loans shape", primary: "G.get200", testFile: "api/loans.test.ts" },
  { id: "G.2", spec: "GET item filter", primary: "G.filter-item", testFile: "api/loans.test.ts" },
  { id: "G.3", spec: "GET overdue filter", primary: "G.filter-overdue", testFile: "api/loans.test.ts" },
  { id: "G.4", spec: "GET intersecting filters", primary: "G.filter-both", testFile: "api/loans.test.ts" },
  { id: "G.5", spec: "POST 201 loan", primary: "G.post201", testFile: "api/loans.test.ts" },
  { id: "G.6", spec: "all methods require staff", primary: "G.401", testFile: "api/loans.test.ts" },
  { id: "G.7", spec: "POST field validation", primary: "G.400", testFile: "api/loans.test.ts" },
  { id: "G.8", spec: "POST on-loan conflict", primary: "G.409", testFile: "api/loans.test.ts" },
  { id: "G.9", spec: "PATCH 200 close", primary: "G.patch200", testFile: "api/loans.test.ts" },
  { id: "G.10", spec: "PATCH no-open-loan conflict", primary: "G.patch409", testFile: "api/loans.test.ts" },
  { id: "G.11", spec: "PATCH field validation", primary: "G.patch400", testFile: "api/loans.test.ts" },
  { id: "G.12", spec: "fresh API responses", primary: "G.fresh", testFile: "api/loans.test.ts" },
  { id: "H.1", spec: "streamed loading heading and six tiles", primary: "H.loading", testFile: "e2e/catalogue.spec.ts" },
  { id: "H.2", spec: "error boundary retry", primary: "H.error", testFile: "e2e/error.spec.ts" },
] as const;
